### ISSUE TITLE
DHT22  / AM2302 running on Odroid C1? / Help

### ISSUE THREAD

**Issue by ludwich66** [technion/lol_dht22#5] opened 2015-09-24 11:36 UTC
Hi i need help,
there are four problems:
1. I am a beginner
2. im a user of a Raspberry (works) and an Odroid C1 (don't work)
3. i don't know how i do fix this configure error 
checking for wiringPiSetup in -lwiringPi... no
configure: error: Fail to find wiringPi library  -> there is a ported wPi version for C1 on github (https://github.com/hardkernel/wiringPi)
-> tests: the libs exists in /usr/lib/ and in ≈/odroid/wiringPi/wiring/pi
-> @libwiringPi.so
-> *libwiringPi.so.2.0 
-> @libwiringPiDev.so 
-> *libwiringPiDev.so.2.0 
...but the configure program don't find it?

4. There is a Userpost in odroid c1 forum, he changed the delaytime from 1 ms to 2 ms (exeperimental but it works for him) 
http://forum.odroid.com/viewtopic.php?f=111&t=14417

Thanks for Hints

ludwich

**Comment by technion** [comment] 2015-09-24 13:06
Hi,

A lot of people have reported this in the last two days. It is caused by a change to wiringPi. I have been  in contact with Gordon from wiringPi and he states a fix is coming.

**Comment by technion** [comment] 2015-09-24 23:20
A fix has been pushed to wiringPi.
https://git.drogon.net/?p=wiringPi;a=commit;h=f6c40cb2a69a43de97903c9fdd6f24a4f32f8eae

Please download and install wiringPi again. This will correct the issue.

**Closed by technion** 2015-09-24 23:20 UTC
